### ISSUE TITLE
Text doesn't render in Firefox 66.0.5/Mac

### ISSUE THREAD

**Issue by swiftcoder** [makepad/makepad#5] opened 2019-05-11 22:05 UTC
Text within the body and the tree control are both invisible on latest Firefox/Mac. Works fine in Safari.

![image](https://user-images.githubusercontent.com/4706210/57575389-db6f3600-7438-11e9-90bd-863b8f6e3b63.png)

**Comment by makepaddev** [comment] 2019-05-11 22:07
Try a shift-reload or cache clean, i can't replicate it.

**Comment by makepaddev** [comment] 2019-05-18 06:15
Closing as can't reproduce

**Comment by swiftcoder** [comment] 2019-06-01 17:05
This is a 100% repro for me. Clearing the cache, disabling ublock origin and ghostery, updating to FIrefox 67.0... Still no luck.

**Comment by makepaddev** [comment] 2019-06-01 17:08
I can't repro it, so i can't fix it. If you want to try you could see if you could run it off local disk (with serve_webgl.sh) and see if its some kind of github hosting issue for the font files.

**Comment by makepaddev** [comment] 2019-06-01 17:12
Other than that its possibly the font shader that wont compile, even though its less complicated than the other shaders that seem to work. My best bet is there is something wrong with the font texture somehwere in the pipeline. But i have ff 67 on mac here doing fine so i can't probe it myself

**Comment by swiftcoder** [comment] 2019-06-01 17:15
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/4706210/58751663-ccf0c900-8490-11e9-9884-db781e5c198c.png">

**Comment by makepaddev** [comment] 2019-06-01 17:17
Ok clear i think your GPU doesn't like 4096 textures. Could you tell me http://renderingpipeline.com/webgl-extension-viewer/
What is says next to MAX_TEXTURE_SIZE

**Comment by makepaddev** [comment] 2019-06-01 17:21
My font textures are 4096x128 or something. Reason is that way you can compress a ton of font in there without messing with multiple textures. But maybe thats not compatible, i could have to resort to 1024x512 or something but that would seriously limit the font table expandability.

**Comment by swiftcoder** [comment] 2019-06-01 17:21
2048 under Firefox, which is more than a little weird, because the native OpenGL stack reports 16k, as do Chrome and Safari.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/4706210/58751696-80f25400-8491-11e9-8526-26a1c6c32922.png">

**Comment by makepaddev** [comment] 2019-06-01 17:22
So yeah someone needs to slap those firefox devs to be normal with their texture size since it really isn't your GPU thats limiting it.

**Comment by makepaddev** [comment] 2019-06-01 17:22
I could change the font format to 2048, i'll contemplate it. thanks for letting me know.

**Comment by makepaddev** [comment] 2019-06-01 17:24
Web, is why we can't have nice things.

**Comment by makepaddev** [comment] 2019-06-01 17:25
Like my entire font-render strategy foiled by some rando restricting firefox to 2048 textures for no apparent reason.

**Comment by makepaddev** [comment] 2019-06-01 17:25
Luckily 4096 isn't reaaally needed i could possibly live without it. I dont need it yet anyway, but once i need to get wider unicodetables i do.

**Comment by makepaddev** [comment] 2019-06-01 17:27
Btw thats some horrendous restriction btw, means your webgl on firefox can't even do 4k native resolution if you do any render to texture caches.

**Comment by swiftcoder** [comment] 2019-06-01 17:27
This bug is reported repeatedly on the Firefox tracker, and several mentions of it being fixed:
https://bugzilla.mozilla.org/show_bug.cgi?id=1310222
https://bugzilla.mozilla.org/show_bug.cgi?id=1200781
https://bugzilla.mozilla.org/show_bug.cgi?id=986871

**Comment by makepaddev** [comment] 2019-06-01 17:28
Luckily im staying away from rendertargets since i haven't found the need for them yet, but dang. Can't i just depricate your config? :)

**Comment by makepaddev** [comment] 2019-06-01 17:29
I can test for it and tell people to use a normal browser :)

**Comment by makepaddev** [comment] 2019-06-01 17:30
Thats not a bad idea btw, i'll make a nice error with a link to the firefox bug so people can pile on.

**Comment by makepaddev** [comment] 2019-08-14 12:00
I'm closing this one, its a *nofix* for now. We are replacing the entire fontstack soon so i can lower the atlas resolution.

**Closed as completed by makepaddev** 2019-08-14 12:00 UTC
